### PR TITLE
feat: shift-click modules to expand/collapse dependencies

### PR DESCRIPTION
**Pull request by broofa**
Shift-click modules in the graph to collapse/expend their dependencies.  Collapsed modules are shown as semi-transparent.

image

This puts the basic code in place for manipulating what modules/dependencies are shown in a graph, so enhancing this to allow for regex-based hiding of modules should be pretty easy.  However ... the reason I went with this approach is that it keeps the parent module in the graph.  This makes it easier to undo the collapse action (parent module is still shift-clickable in the graph), and it makes it clear where modules have been removed from the graph.

@bennycode: This isn't quite what you're asking for in #47, but it's a step in the right direction.

(@fregante Does switching to Vercel remove the need to commit the `parcel build` output (/docs/* in this diff)?    'Would love to not have that be part of the commit step.)

### CODE REVIEW

**Comment by fregante** [comment]
The was never a need to commit the docs folder on the main branch. The original idea was to push to the gh-pages branch like the workflow I linked to did.

Anyway, yes. Vercel builds and hosts the file, so it just needs the source.

**Comment by fregante** [comment]
Seems to work well and it's useful! One small issue is due to how `shift` works (in Safari only). I think it just needs a `e.preventDefault()`

gif

**Comment by broofa** [comment]
> Seems to work well and it's useful! One small issue is due to how `shift` works (in Safari only). I think it just needs a `e.preventDefault()`

You mean the brief text-selection flash?  Looks like that's because Safari requires the "-webkit-" prefix for the `user-select` CSS property.  Should be fixed now.

**Comment by broofa** [comment]
@fregante Okay to merge?

**Pull request merged**
